# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AutoFocus_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  AutoFocus_config = release
  Sandbox_config = release
endif

PROJECTS := AutoFocus Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AutoFocus:
ifneq (,$(AutoFocus_config))
	@echo "==== Building AutoFocus ($(AutoFocus_config)) ===="
	@${MAKE} --no-print-directory -C AutoFocus -f Makefile config=$(AutoFocus_config)
endif

Sandbox: AutoFocus
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C AutoFocus -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AutoFocus"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"